# Generated by Django 4.0.2 on 2022-04-27 20:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ingredients', models.TextField(default='')),
                ('instructions', models.TextField(default='')),
                ('photo', models.ImageField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='')),
                ('author', models.CharField(default='anonymous', max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MultiRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('descriptions', models.JSONField(default=list)),
                ('recipes', models.JSONField(default=list)),
                ('author', models.CharField(default='anonymous', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ingredients', models.TextField(default='')),
                ('recipe', models.TextField(default='')),
                ('photo', models.ImageField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='')),
                ('likes', models.IntegerField(default=0)),
                ('author', models.CharField(default='anonymous', max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ForkComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wordofmouth.fork')),
            ],
            options={
                'ordering': ['time_posted'],
            },
        ),
        migrations.AddField(
            model_name='fork',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forks', to='wordofmouth.recipe'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wordofmouth.recipe')),
            ],
            options={
                'ordering': ['time_posted'],
            },
        ),
    ]
