"""
Django settings for wordofmouth project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os

import sys

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@d)6@3%&jbe!u$-y@x+qob_1x7$bfzj1cf0qmk@!i!zwnadsh8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['wordofmouth-b01.herokuapp.com', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'wordofmouth.apps.WordOfMouthConfig',
    'bootstrap5',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'gdstorage',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wordofmouth.urls'

'''
Title: Django Google Drive Storage
Author: torre76, conformist-mw, mca10, codingjoe, ex5, marcgibbons, MarlonJD, thismatters, ugaemi,
        gunthercox, mhsekhavat, saileshdev, flywindy, CristianFonseca03
Date: 05/11/2014 - 11/28/2021
Code version: 1.6.0
URL: https://django-googledrive-storage.readthedocs.io/en/latest/
Software License: BSD-3
'''
'''
Title: django [Errno2] No such file or directory:
Author: eaithy
Date: 01/07/2020
Code version: Django v4.0
URL: https://stackoverflow.com/questions/21370298/django-errno-2-no-such-file-or-directory
Software License: BSD
'''


GOOGLE_DRIVE_STORAGE_JSON_KEY_FILE = os.path.join(BASE_DIR, 'static/admin/wordofmouth-b01-9c1309a4dbd2.json')
#GOOGLE_DRIVE_STORAGE_MEDIA_ROOT = '<base google drive path for file uploads>' # OPTIONAL

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'wordofmouth/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

WSGI_APPLICATION = 'wordofmouth.wsgi.application'


# Database
'''
Title: Settings
Author: Django Software Foundation and individual contributors
Date: 2005-2022
Code version: Django v4.0
URL: https://docs.djangoproject.com/en/4.0/ref/settings/#databases
Software License: BSD
'''

# update database info based on Piazza post @62
if 'test' in sys.argv:
    SECURE_SSL_REDIRECT=False
    DATABASES = {
        'default':{
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME':  BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # does NOT work locally - for deployment only!
    '''
    Title: Security in Django
    Author: Django Software Foundation and individual contributors
    Date: 2005-2022
    Code version: Django v2.2
    URL: https://docs.djangoproject.com/en/2.2/topics/security/#ssl-https
    Software License: BSD
    '''
    SECURE_SSL_REDIRECT=True
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'dbrdj94t5r46oi',
            'USER': 'eujlppwgibapgw',
            'PASSWORD': '61ed30e5b74d274644264fb1472bdacc8a4645f0b8bb79b894f9e746b8d01d49',
            'HOST': 'ec2-3-219-204-29.compute-1.amazonaws.com',
            'PORT': '5432',
        }
    }



# Password validation
'''
Title: Settings
Author: Django Software Foundation and individual contributors
Date: 2005-2022
Code version: Django v4.0
URL: https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators
Software License: BSD
'''

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
'''
Title: Internationalization and localization
Author: Django Software Foundation and individual contributors
Date: 2005-2022
Code version: Django v4.0
URL: https://docs.djangoproject.com/en/4.0/topics/i18n/
Software License: BSD
'''

LANGUAGE_CODE = 'en-us'

'''
Title: Python time zones: Why is EST off by one hour? (pytz/dateutil)
Author: Matt Johnson-Pint
Date: 10/01/2020
Code version: Django v4.0
URL: https://stackoverflow.com/questions/64159241/python-time-zones-why-is-est-off-by-one-hour-pytz-dateutil
Software License: BSD
'''

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
'''
Title: How to manage static files (e.g. images, JavaScript, CSS)
Author: Django Software Foundation and individual contributors
Date: 2005-2022
Code version: Django v4.0
URL: https://docs.djangoproject.com/en/4.0/howto/static-files/
Software License: BSD
'''

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
'''
Title: Settings
Author: Django Software Foundation and individual contributors
Date: 2005-2022
Code version: Django v4.0
URL: https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field
Software License: BSD
'''

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


SITE_ID = 3 # there was already an "example.com" as site id 1

'''
Title: Configuration
Author: pennersr, julen, stantond, jleclanche, berkerpeksag, ERM, hartym, danidee10, mick88, 
        matthijskooijman, manuganji, LuanP, iarp, gionniboy, jessamynsmith, Flimm, BernhardPosselt, 
        esacteksab, aagustin, AstraLuma
Date: 2017 - 2022
Code version: 7.6.2
URL: https://django-allauth.readthedocs.io/en/latest/configuration.html
Software License: MIT
'''
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
"""
# Additional configuration settings
SOCIALACCOUNT_QUERY_EMAIL = True
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_REQUIRED = True 
"""
LOGIN_REDIRECT_URL = '/'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

try:
    if 'HEROKU' in os.environ:
        import django_heroku
        django_heroku.settings(locals())
except ImportError:
    found = False
